export const UPDATE_LOGIN_FORM = '@LOGIN/UPDATE_LOGIN_FORM';
export const CLEAR_LOGIN_FORM = '@LOGIN/CLEAR_LOGIN_FORM';

export const LOGIN_INIT = '@LOGIN/LOGIN_INIT';
export const LOGIN_SUCCESS = '@LOGIN/LOGIN_SUCCESS';
export const LOGIN_FAILURE = '@LOGIN/LOGIN_FAILURE';

export const UPDATE_REGISTER_FORM = '@REGISTER/UPDATE_REGISTER_FORM';
export const CLEAR_REGISTER_FORM = '@REGISTER/CLEAR_REGISTER_FORM';

export const UPDATE_NEW_CAR_FORM = '@CARS/UPDATE_NEW_CAR_FORM';
export const CLEAR_NEW_CAR_FORM = '@CARS/CLEAR_NEW_CAR_FORM';

export const UPDATE_UPDATE_CAR_FORM = '@CARS/UPDATE_UPDATE_CAR_FORM';
export const CLEAR_UPDATE_CAR_FORM = '@CARS/CLEAR_UPDATE_CAR_FORM';

export const UPDATE_UPDATE_RESERVATION_FORM = '@RESERVATIONS/UPDATE_UPDATE_RESERVATION_FORM';
export const CLEAR_UPDATE_RESERVATION_FORM = '@RESERVATIONS/CLEAR_UPDATE_RESERVATION_FORM';

export const REGISTER_INIT = '@REGISTER/REGISTER_INIT';
export const REGISTER_SUCCESS = '@REGISTER/REGISTER_SUCCESS';
export const REGISTER_FAILURE = '@REGISTER/REGISTER_FAILURE';

export const LOGOUT_INIT = '@LOGOUT/LOGOUT_INIT';
export const LOGOUT_SUCCESS = '@LOGOUT/LOGOUT_SUCCESS';
export const LOGOUT_FAILURE = '@LOGOUT/LOGOUT_FAILURE';

export const FETCH_CARS_INIT = '@CARS/FETCH_CARS_INIT';
export const FETCH_CARS_SUCCESS = '@CARS/FETCH_CARS_SUCCESS';
export const FETCH_CARS_FAILURE = '@CARS/FETCH_CARS_FAILURE';

export const ADD_CAR_INIT = '@CARS/ADD_CAR_INIT';
export const ADD_CAR_SUCCESS = '@CARS/ADD_CAR_SUCCESS';
export const ADD_CAR_FAILURE = '@CARS/ADD_CAR_FAILURE';

export const UPDATE_CAR_INIT = '@CARS/UPDATE_CAR_INIT';
export const UPDATE_CAR_SUCCESS = '@CARS/UPDATE_CAR_SUCCESS';
export const UPDATE_CAR_FAILURE = '@CARS/UPDATE_CAR_FAILURE';

export const DELETE_CAR_INIT = '@CARS/DELETE_CAR_INIT';
export const DELETE_CAR_SUCCESS = '@CARS/DELETE_CAR_SUCCESS';
export const DELETE_CAR_FAILURE = '@CARS/DELETE_CAR_FAILURE';

export const FETCH_RESERVATIONS_INIT = '@RESERVATIONS/FETCH_RESERVATIONS_INIT';
export const FETCH_RESERVATIONS_SUCCESS = '@RESERVATIONS/FETCH_RESERVATIONS_SUCCESS';
export const FETCH_RESERVATIONS_FAILURE = '@RESERVATIONS/FETCH_RESERVATIONS_FAILURE';

export const CREATE_RESERVATION_INIT = '@RESERVATIONS/CREATE_RESERVATION_INIT';
export const CREATE_RESERVATION_SUCCESS = '@RESERVATIONS/CREATE_RESERVATION_SUCCESS';
export const CREATE_RESERVATION_FAILURE = '@RESERVATIONS/CREATE_RESERVATION_FAILURE';

export const UPDATE_RESERVATION_INIT = '@RESERVATIONS/UPDATE_RESERVATION_INIT';
export const UPDATE_RESERVATION_SUCCESS = '@RESERVATIONS/UPDATE_RESERVATION_SUCCESS';
export const UPDATE_RESERVATION_FAILURE = '@RESERVATIONS/UPDATE_RESERVATION_FAILURE';

export const CHECK_AVAILABILITY_INIT = '@CARS/CHECK_AVAILABILITY_INIT';
export const CHECK_AVAILABILITY_SUCCESS = '@CARS/CHECK_AVAILABILITY_SUCCESS';
export const CHECK_AVAILABILITY_FAILURE = '@CARS/CHECK_AVAILABILITY_FAILURE';

export const UPDATE_RESERVATION_FORM = '@RESERVATIONS/UPDATE_RESERVATION_FORM';
export const CLEAR_RESERVATION_FORM = '@RESERVATIONS/CLEAR_RESERVATION_FORM';

export const FETCH_USER_INIT = '@USER/FETCH_USER_INIT';
export const FETCH_USER_SUCCESS = '@USER/FETCH_USER_SUCCESS';
export const FETCH_USER_FAILURE = '@USER/FETCH_USER_FAILURE';
